Repository kcc-finalproject/kcc_bus_reservation_system, pull requests merged in 2024-09, with the labels that each got.

#36 [Style]Main 페이지 modal 연결 #35
  .idea/vcs.xml
  .idea/workspace.xml
  backend/src/main/webapp/WEB-INF/views/main.jsp
  frontend/css/main.css
  frontend/img/payment_icon_yellow_medium.png
  frontend/img/payment_icon_yellow_small.png
  frontend/js/main.js
Labels: 🎨Html&css

#37 [Style]: html to jsp convert #21
  .idea/.gitignore
  .idea/compiler.xml
  .idea/kcc_bus_reservation_system.iml
  .idea/misc.xml
  .idea/modules.xml
  .vscode/settings.json
  backend/src/main/java/com/unibus/user/controller/MainController.java
  backend/src/main/java/com/unibus/user/controller/UserController.java
  backend/src/main/webapp/WEB-INF/views/main.jsp
  backend/src/main/webapp/resources/img/bus_bg.png
  backend/src/main/webapp/resources/img/bus_bg_big.png
  backend/src/main/webapp/resources/img/main_view.jpg
  backend/src/main/webapp/resources/js/header.js
Labels: 🎨Html&css

#39 [Feature]: admin user delete 구현 #28
  backend/src/main/java/com/unibus/admin/controller/AdminController.java
  backend/src/main/java/com/unibus/admin/mapper/AdminMapper.java
  backend/src/main/java/com/unibus/admin/service/AdminService.java
  backend/src/main/java/com/unibus/admin/service/AdminServiceImpl.java
  backend/src/main/java/com/unibus/user/controller/UserController.java
  backend/src/main/resources/mapper/admin/adminMapper.xml
  backend/src/main/webapp/WEB-INF/views/login.jsp
  backend/src/main/webapp/WEB-INF/views/membership.jsp
Labels: ✨Feature

#43 [Feature] admin terminal 기능 구현
  backend/src/main/java/com/unibus/admin/controller/AdminController.java
  backend/src/main/java/com/unibus/admin/domain/City.java
  backend/src/main/java/com/unibus/admin/domain/Terminal.java
  backend/src/main/java/com/unibus/admin/domain/User.java
  backend/src/main/java/com/unibus/admin/dto/AdminTerminalDto.java
  backend/src/main/java/com/unibus/admin/dto/UpdateTerminalDto.java
  backend/src/main/java/com/unibus/admin/dto/UserDto.java
  backend/src/main/java/com/unibus/admin/mapper/AdminMapper.java
  backend/src/main/java/com/unibus/admin/service/AdminService.java
  backend/src/main/java/com/unibus/admin/service/AdminServiceImpl.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/admin/adminMapper.xml
  backend/src/main/webapp/WEB-INF/views/admin_terminal.jsp
  frontend/css/admin_terminal.css
  frontend/js/admin_terminal.js
Labels: ✨Feature

#46 [Feature] admin company 기능 구현
  backend/src/main/java/com/unibus/admin/controller/AdminController.java
  backend/src/main/java/com/unibus/admin/domain/Bus.java
  backend/src/main/java/com/unibus/admin/domain/Company.java
  backend/src/main/java/com/unibus/admin/dto/CompanyDto.java
  backend/src/main/java/com/unibus/admin/mapper/AdminMapper.java
  backend/src/main/java/com/unibus/admin/service/AdminService.java
  backend/src/main/java/com/unibus/admin/service/AdminServiceImpl.java
  backend/src/main/resources/mapper/admin/adminMapper.xml
Labels: ✨Feature

#48 ID 중복검사, 회원정보 수정, 회원정보 조회, 회원 탈퇴 API 기능 생성 #47
  backend/src/main/java/com/unibus/user/controller/UserController.java
  backend/src/main/java/com/unibus/user/mapper/UserMapper.java
  backend/src/main/java/com/unibus/user/service/UserService.java
  backend/src/main/java/com/unibus/user/service/UserServiceImpl.java
  backend/src/main/resources/mapper/user/userMapper.xml
Labels: ✨Feature

#49 [Feature] admin route 기능 구현
  backend/src/main/java/com/unibus/admin/controller/AdminController.java
  backend/src/main/java/com/unibus/admin/domain/Route.java
  backend/src/main/java/com/unibus/admin/dto/RouteCreateDto.java
  backend/src/main/java/com/unibus/admin/dto/RouteDto.java
  backend/src/main/java/com/unibus/admin/dto/TerminalDto.java
  backend/src/main/java/com/unibus/admin/mapper/AdminMapper.java
  backend/src/main/java/com/unibus/admin/service/AdminService.java
  backend/src/main/java/com/unibus/admin/service/AdminServiceImpl.java
  backend/src/main/resources/mapper/admin/adminMapper.xml
Labels: ✨Feature

#51 mypage.js, mypage_edit.js, login.jsp, membership.jsp, 로그인 구현, 회원가입 구현 #50
  .idea/misc.xml
  .idea/workspace.xml
  backend/pom.xml
  backend/src/main/java/com/unibus/config/PrincipalDetail.java
  backend/src/main/java/com/unibus/config/PrincipalDetailService.java
  backend/src/main/java/com/unibus/config/SecurityConfig.java
  backend/src/main/java/com/unibus/user/controller/UserController.java
  backend/src/main/java/com/unibus/user/domain/Member.java
  backend/src/main/java/com/unibus/user/dto/ValidPassword.java
  backend/src/main/java/com/unibus/user/mapper/UserMapper.java
  backend/src/main/java/com/unibus/user/service/UserService.java
  backend/src/main/java/com/unibus/user/service/UserServiceImpl.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/user/userMapper.xml
  backend/src/main/webapp/WEB-INF/views/login.jsp
  backend/src/main/webapp/WEB-INF/views/membership.jsp
  backend/src/main/webapp/WEB-INF/views/mypage.jsp
  backend/src/main/webapp/WEB-INF/views/mypage_edit.jsp
  backend/src/main/webapp/resources/css/mypage _edit.css
  backend/src/main/webapp/resources/css/mypage.css
  backend/src/main/webapp/resources/js/mypage.js
  backend/src/main/webapp/resources/js/mypage_edit.js
Labels: ✨Feature

#54 [Feature] ScheduleController, TerminalController ,main.js, 기능구현 #53
  backend/src/main/java/com/unibus/Exception/CustomizedResponseEntityExceptionHandler.java
  backend/src/main/java/com/unibus/reservation/controller/ReservationController.java
  backend/src/main/java/com/unibus/reservation/controller/ScheduleController.java
  backend/src/main/java/com/unibus/reservation/controller/TerminalController.java
  backend/src/main/java/com/unibus/reservation/domain/Reservation.java
  backend/src/main/java/com/unibus/reservation/domain/Schedule.java
  backend/src/main/java/com/unibus/reservation/domain/Terminal.java
  backend/src/main/java/com/unibus/reservation/dto/ReservationDto.java
  backend/src/main/java/com/unibus/reservation/dto/ScheduleDto.java
  backend/src/main/java/com/unibus/reservation/dto/TerminalDto.java
  backend/src/main/java/com/unibus/reservation/mapper/ReservationMapper.java
  backend/src/main/java/com/unibus/reservation/mapper/ScheduleMapper.java
  backend/src/main/java/com/unibus/reservation/mapper/TerminalMapper.java
  backend/src/main/java/com/unibus/reservation/service/ReservationService.java
  backend/src/main/java/com/unibus/reservation/service/ScheduleService.java
  backend/src/main/java/com/unibus/reservation/service/ScheduleServiceImpl.java
  backend/src/main/java/com/unibus/reservation/service/TerminalService.java
  backend/src/main/java/com/unibus/reservation/service/TerminalServiceImpl.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/reservation/reservationMapper.xml
  backend/src/main/resources/mapper/reservation/scheduleMapper.xml
  backend/src/main/resources/mapper/reservation/terminalMapper.xml
  backend/src/main/webapp/WEB-INF/views/main.jsp
  backend/src/main/webapp/resources/css/main.css
  backend/src/main/webapp/resources/js/main.js
Labels: ✨Feature, 🎨Html&css

#55 [Feature] security 구현
  backend/src/main/java/com/unibus/Exception/CustomizedResponseEntityExceptionHandler.java
  backend/src/main/java/com/unibus/config/PrincipalDetail.java
  backend/src/main/java/com/unibus/config/PrincipalDetailService.java
  backend/src/main/java/com/unibus/config/SecurityConfig.java
  backend/src/main/java/com/unibus/user/controller/MainController.java
  backend/src/main/java/com/unibus/user/controller/UserController.java
  backend/src/main/java/com/unibus/user/domain/Member.java
  backend/src/main/java/com/unibus/user/mapper/UserMapper.java
  backend/src/main/java/com/unibus/user/service/UserService.java
  backend/src/main/java/com/unibus/user/service/UserServiceImpl.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/user/userMapper.xml
  backend/src/main/webapp/WEB-INF/views/login.jsp
  backend/src/main/webapp/WEB-INF/views/membership.jsp
  backend/src/main/webapp/WEB-INF/views/mypage.jsp
  backend/src/main/webapp/WEB-INF/views/mypage_edit.jsp
  backend/src/main/webapp/resources/css/mypage _edit.css
  backend/src/main/webapp/resources/js/mypage_edit.js
  backend/src/main/webapp/resources/js/user_header.js
Labels: ✨Feature

#56 [Feature] 로그인 핸들러, 로그인, 회원탈퇴 시큐리티 생성 및 변경 #52
  backend/src/main/java/com/unibus/reservation/controller/ReservationController.java
  backend/src/main/java/com/unibus/reservation/mapper/ReservationMapper.java
  backend/src/main/java/com/unibus/reservation/service/ReservationService.java
  backend/src/main/java/com/unibus/reservation/service/ReservationServiceImpl.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/reservation/reservationMapper.xml
  backend/src/main/webapp/WEB-INF/views/payment.jsp
  backend/src/main/webapp/resources/css/payment.css
  backend/src/main/webapp/resources/js/payment.js
Labels: ✨Feature

#59 [Feature] main.jsp 출발, 도착지, 날짜 선택, resevation_detail.jsp 목록 동적생성 #58
  backend/src/main/java/com/unibus/reservation/controller/ScheduleController.java
  backend/src/main/java/com/unibus/reservation/domain/Schedule.java
  backend/src/main/java/com/unibus/reservation/dto/ScheduleDto.java
  backend/src/main/java/com/unibus/reservation/mapper/ScheduleMapper.java
  backend/src/main/java/com/unibus/reservation/mapper/TerminalMapper.java
  backend/src/main/java/com/unibus/reservation/service/ScheduleServiceImpl.java
  backend/src/main/java/com/unibus/reservation/service/TerminalService.java
  backend/src/main/java/com/unibus/reservation/service/TerminalServiceImpl.java
  backend/src/main/resources/mapper/reservation/scheduleMapper.xml
  backend/src/main/resources/mapper/reservation/terminalMapper.xml
  backend/src/main/webapp/WEB-INF/views/main.jsp
  backend/src/main/webapp/WEB-INF/views/reservation_detail.jsp
  backend/src/main/webapp/resources/css/main.css
  backend/src/main/webapp/resources/css/reservaton_detail.css
  backend/src/main/webapp/resources/js/main.js
  backend/src/main/webapp/resources/js/reservation_detail.js
Labels: ✨Feature

#61 [Feature] 버스 등급별 좌석 페이지 연동, 관리자 회원관리, 메인 달력 이전날짜 제한 #60
  backend/src/main/java/com/unibus/config/SecurityConfig.java
  backend/src/main/java/com/unibus/reservation/controller/ReservationController.java
  backend/src/main/java/com/unibus/reservation/controller/ScheduleController.java
  backend/src/main/java/com/unibus/reservation/controller/TerminalController.java
  backend/src/main/java/com/unibus/reservation/domain/Reservation.java
  backend/src/main/java/com/unibus/reservation/dto/ReservationSummaryDTO.java
  backend/src/main/java/com/unibus/reservation/dto/ScheduleSeatNumber.java
  backend/src/main/java/com/unibus/reservation/mapper/ReservationMapper.java
  backend/src/main/java/com/unibus/reservation/mapper/ScheduleMapper.java
  backend/src/main/java/com/unibus/reservation/mapper/TerminalMapper.java
  backend/src/main/java/com/unibus/reservation/service/ReservationService.java
  backend/src/main/java/com/unibus/reservation/service/ReservationServiceImpl.java
  backend/src/main/java/com/unibus/reservation/service/ScheduleService.java
  backend/src/main/java/com/unibus/reservation/service/ScheduleServiceImpl.java
  backend/src/main/java/com/unibus/reservation/service/TerminalService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/reservation/reservationMapper.xml
  backend/src/main/resources/mapper/reservation/scheduleMapper.xml
  backend/src/main/webapp/WEB-INF/views/admin_user.jsp
  backend/src/main/webapp/WEB-INF/views/mypage_reservation_list.jsp
  backend/src/main/webapp/resources/css/main.css
  backend/src/main/webapp/resources/css/reservation_seat1.css
  backend/src/main/webapp/resources/css/reservation_seat2.css
  backend/src/main/webapp/resources/css/reservation_seat3.css
  backend/src/main/webapp/resources/js/admin_user.js
  backend/src/main/webapp/resources/js/main.js
  backend/src/main/webapp/resources/js/mypage_reservation_list.js
  backend/src/main/webapp/resources/js/reservation_seat.js
Labels: ✨Feature

#67 [Feature] 버스좌석 실제 좌석 연동 및 이벤트 제어, 관리자 회원관리 검색 구현 #66
  backend/src/main/java/com/unibus/reservation/controller/ReservationController.java
  backend/src/main/java/com/unibus/reservation/controller/ScheduleController.java
  backend/src/main/java/com/unibus/reservation/dto/ReservationTicketDto.java
  backend/src/main/java/com/unibus/reservation/dto/ScheduleSeatNumber.java
  backend/src/main/java/com/unibus/reservation/mapper/ReservationMapper.java
  backend/src/main/java/com/unibus/reservation/service/ReservationService.java
  backend/src/main/java/com/unibus/reservation/service/ReservationServiceImpl.java
  backend/src/main/resources/mapper/reservation/reservationMapper.xml
  backend/src/main/resources/mapper/reservation/scheduleMapper.xml
  backend/src/main/webapp/WEB-INF/views/admin_user.jsp
  backend/src/main/webapp/WEB-INF/views/payment_accept.jsp
  backend/src/main/webapp/WEB-INF/views/reservation_detail.jsp
  backend/src/main/webapp/WEB-INF/views/reservation_seat1.jsp
  backend/src/main/webapp/WEB-INF/views/reservation_seat2.jsp
  backend/src/main/webapp/WEB-INF/views/reservation_seat3.jsp
  backend/src/main/webapp/resources/css/admin_user.css
  backend/src/main/webapp/resources/css/reservation_seat1.css
  backend/src/main/webapp/resources/css/reservation_seat2.css
  backend/src/main/webapp/resources/css/reservation_seat3.css
  backend/src/main/webapp/resources/css/reservaton_detail.css
  backend/src/main/webapp/resources/js/admin_user.js
  backend/src/main/webapp/resources/js/payment.js
  backend/src/main/webapp/resources/js/reservation_detail.js
  backend/src/main/webapp/resources/js/reservation_seat.js
  frontend/.vscode/settings.json
Labels: ✨Feature

#68 [Feature]: admin schedule 기능 구현
  backend/src/main/java/com/unibus/admin/controller/AdminController.java
  backend/src/main/java/com/unibus/admin/domain/AdminSchedule.java
  backend/src/main/java/com/unibus/admin/dto/AdminScheduleDto.java
  backend/src/main/java/com/unibus/admin/dto/CompanyAndBusDto.java
  backend/src/main/java/com/unibus/admin/dto/CreateScheduleDto.java
  backend/src/main/java/com/unibus/admin/dto/GetRouteIdVo.java
  backend/src/main/java/com/unibus/admin/dto/SchedulePageDto.java
  backend/src/main/java/com/unibus/admin/mapper/AdminMapper.java
  backend/src/main/java/com/unibus/admin/service/AdminService.java
  backend/src/main/java/com/unibus/admin/service/AdminServiceImpl.java
  backend/src/main/resources/mapper/admin/adminMapper.xml
  backend/src/main/webapp/WEB-INF/views/admin_schedule.jsp
  backend/src/main/webapp/resources/css/admin_schedule.css
  backend/src/main/webapp/resources/js/admin_paging.js
  backend/src/main/webapp/resources/js/admin_schedule.js
Labels: ✨Feature

#69 [Feature] main.jsp 출발, 도착지, 날짜 선택, resevation_detail.jsp 목록 동적생성 #58
  backend/src/main/java/com/unibus/admin/controller/AdminController.java
  backend/src/main/java/com/unibus/admin/service/AdminServiceImpl.java
  backend/src/main/java/com/unibus/config/SecurityConfig.java
  backend/src/main/java/com/unibus/reservation/controller/ScheduleController.java
  backend/src/main/webapp/WEB-INF/views/admin_terminal.jsp
  backend/src/main/webapp/WEB-INF/views/main.jsp
  backend/src/main/webapp/resources/css/admin_terminal.css
  backend/src/main/webapp/resources/css/main.css
  backend/src/main/webapp/resources/img/main_view2.jpg
  backend/src/main/webapp/resources/img/main_view2.png
  backend/src/main/webapp/resources/img/main_view3.jpg
  backend/src/main/webapp/resources/img/main_view4.jpg
  backend/src/main/webapp/resources/js/admin_terminal.js
  backend/src/main/webapp/resources/js/main.js
  frontend/img/main.jpg
  frontend/img/main_view2.jpg
  frontend/img/main_view3.png
  frontend/img/main_view4.jpg
Labels: ✨Feature

#74 [Feature] 회원 예약내역, 예약 상세내역 보여주는 view 완성 #73
  backend/src/main/java/com/unibus/reservation/controller/ReservationController.java
  backend/src/main/java/com/unibus/reservation/controller/ScheduleController.java
  backend/src/main/java/com/unibus/reservation/dto/ReservationFinishDto.java
  backend/src/main/java/com/unibus/reservation/dto/ReservationSummaryDTO.java
  backend/src/main/java/com/unibus/reservation/mapper/ReservationMapper.java
  backend/src/main/java/com/unibus/reservation/service/ReservationService.java
  backend/src/main/java/com/unibus/reservation/service/ReservationServiceImpl.java
  backend/src/main/java/com/unibus/user/controller/MainController.java
  backend/src/main/java/com/unibus/user/controller/UserController.java
  backend/src/main/resources/mapper/reservation/reservationMapper.xml
  backend/src/main/webapp/WEB-INF/views/mypage.jsp
  backend/src/main/webapp/WEB-INF/views/mypage_reservation_list.jsp
  backend/src/main/webapp/WEB-INF/views/payment_finish.jsp
  backend/src/main/webapp/WEB-INF/views/reservation_detail.jsp
  backend/src/main/webapp/resources/css/mypage.css
  backend/src/main/webapp/resources/css/payment.css
  backend/src/main/webapp/resources/js/mypage_reservation_list.js
  backend/src/main/webapp/resources/js/payment.js
  backend/src/main/webapp/resources/js/payment_finish.js
  backend/src/main/webapp/resources/js/user_header.js
  backend/src/test/java/com/unibus/BackendApplicationTests.java
Labels: ✨Feature

#75 [Feature]: logout 기능 구현 #72
  backend/src/main/java/com/unibus/config/SecurityConfig.java
  backend/src/main/java/com/unibus/user/mapper/UserMapper.java
  backend/src/main/java/com/unibus/user/service/UserService.java
  backend/src/main/java/com/unibus/user/service/UserServiceImpl.java
  backend/src/main/resources/mapper/user/userMapper.xml
Labels: ✨Feature

#77 feature:버스 결제, 마이페이지 연동 #76
  backend/src/main/java/com/unibus/admin/controller/AdminController.java
  backend/src/main/java/com/unibus/admin/dto/SearchMemberDTO.java
  backend/src/main/java/com/unibus/admin/mapper/AdminMapper.java
  backend/src/main/java/com/unibus/admin/service/AdminService.java
  backend/src/main/java/com/unibus/admin/service/AdminServiceImpl.java
  backend/src/main/java/com/unibus/reservation/controller/ReservationController.java
  backend/src/main/java/com/unibus/reservation/controller/ScheduleController.java
  backend/src/main/java/com/unibus/reservation/dto/ReservationTicketDto.java
  backend/src/main/java/com/unibus/reservation/dto/ScheduleSeatNumber.java
  backend/src/main/resources/mapper/reservation/reservationMapper.xml
  backend/src/main/resources/mapper/reservation/scheduleMapper.xml
  backend/src/main/webapp/WEB-INF/views/admin_user.jsp
  backend/src/main/webapp/WEB-INF/views/payment.jsp
  backend/src/main/webapp/WEB-INF/views/payment_accept.jsp
  backend/src/main/webapp/WEB-INF/views/reservation_seat3.jsp
  backend/src/main/webapp/resources/js/admin_header.js
  backend/src/main/webapp/resources/js/header.js
  backend/src/main/webapp/resources/js/payment.js
  backend/src/main/webapp/resources/js/payment_accept.js
  backend/src/main/webapp/resources/js/payment_last.js
  backend/src/main/webapp/resources/js/reservation_seat.js
  backend/src/main/webapp/resources/js/user_header.js
Labels: ✨Feature

#79 [Feature] role에 따른 login success 경로 수정 및 route페이지 수정
  backend/pom.xml
  backend/src/main/java/com/unibus/admin/controller/AdminController.java
  backend/src/main/java/com/unibus/config/CustomAuthenticationSuccessHandler.java
  backend/src/main/java/com/unibus/config/SecurityConfig.java
  backend/src/main/java/com/unibus/user/controller/UserController.java
  backend/src/main/java/com/unibus/user/dto/ValidPassword.java
  backend/src/main/java/com/unibus/user/service/UserServiceImpl.java
  backend/src/main/webapp/WEB-INF/views/admin_route.jsp
  backend/src/main/webapp/WEB-INF/views/admin_schedule.jsp
  backend/src/main/webapp/resources/js/admin_header.js
  backend/src/main/webapp/resources/js/admin_route.js
  backend/src/main/webapp/resources/js/admin_terminal.js
Labels: ✨Feature
